spring.application.name=dr-screening

spring.datasource.url=jdbc:postgresql://localhost:5432/dr_screening
spring.datasource.username=dr_app
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ml.service.url=http://localhost:8000